---
# https://docs.ansible.com/ansible/latest/collections/community/general/redhat_subscription_module.html
- name: "Register System with RedHat"
  hosts: "{{ hostlist | default('127.0.0.1') }}"
  become: true

  tasks:
    - block:
        - name: "Register our system"
          community.general.redhat_subscription:
            state: present
            username: "{{ rhel_username }}"
            password: "{{ rhel_password }}"
            auto_attach: true
          no_log: True
      when:
        - rhel_username is defined and rhel_password is defined and ansible_distribution == "RedHat"

    - block:
        - name: "Deregister our system"
          community.general.redhat_subscription:
            state: absent
      when:
        - rhel_username is not defined and rhel_password is not defined and ansible_distribution == "RedHat"
...